using AutoFixture.Kernel;
using System;
using System.Reflection;

namespace FluentAssertions.Properties.Tests.Common
{
    /// <summary>
    /// FluentAssertions ensures that the 'because' argument is prefixed with the word 'because'.
    /// AutoFixture prefixes the autogenerated string values with the name of the property.
    /// When the property begins with 'because' this may create confusion. 
    /// This specimen builder for AutoFixture does not add any prefix to the generated string values
    /// and can therefore safely be used with FluentAssertions in the tests.
    /// </summary>
    internal class AutoFixtureNonPrefixedStringGenerator : ISpecimenBuilder
    {
        public object Create(object request, ISpecimenContext context)
        {
            if (request is PropertyInfo propInfo 
                && propInfo.PropertyType.Equals(typeof(string)))
            {
                return Guid.NewGuid().ToString();
            }

            return new NoSpecimen();
        }
    }
}
